Add tip about Comment Block style within JSX
facebook/docusaurus pull request #10066
Opened 2024-04-21 01:28 UTC by thadguidry

- Adds tip admonition about JSX comment blocks just before we introduce some info about Prettier and using a JSX comment block
- This is also useful context later in the page where we talk about React component styling a bit.

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

2024-04-21 04:08 UTC, Josh-Cena requested changes
This should be put in the markdown features file instead. This doc is for how MDX and React interop (importing/exporting components, etc.)

2024-04-25 11:26 UTC, slorber reviewed
> we don't want to teach everything about JSX

Yes 👍 there are many other JSX things that we don't mention here, and we already link to the MDX docs for those that want to know more.

---

Thanks for your proposal, and I'm not against mentioning comments, but if you care about this addition, please open a real PR (not from a patch-1 branch), ensure it passes linting, and keep the information as concise as possible, and 100% accurate.

2024-04-25 11:26 UTC, slorber commented on website/docs/guides/markdown-features/markdown-features-intro.mdx
> +```
This is too verbose for me just to explain we should use `{/* comment */}` syntax in MDX. Even the MDX docs is less verbose than this when explaining comments: https://mdxjs.com/docs/what-is-mdx/



This does does not take into account that we also have a commonmark mode that still allows to use HTML comment. 

We also have a v3 compat	option to support HTML comments in MDX that is turned on by default: https://docusaurus.io/docs/migration/v3#comments-option

2024-04-25 11:26 UTC, closed without merging

2024-04-25 11:28 UTC, thadguidry commented
@slorber no worries.  Until next time! :-)