Fixed wrong et translations and typos
facebook/docusaurus pull request #10344
Opened 2024-07-28 17:12 UTC by Gekd

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fix Estonian default translations.

## Related issues/PRs

https://github.com/facebook/docusaurus/issues/3526

2024-07-29 07:57 UTC, slorber requested changes
Thanks,

LGTM but I don't speak Estonian 😅 

Little linting issues

This language has only been added recently. Can you help review it @chirbard please?

2024-07-29 07:57 UTC, slorber commented on packages/docusaurus-theme-translations/locales/et/theme-search-algolia.json
> -}
please remove the extra line breaks here, our linter won't le me merge with it

2024-07-30 06:23 UTC, chirbard commented on packages/docusaurus-theme-translations/locales/et/theme-live-codeblock.json
> +  "theme.Playground.liveEditor": "Elav Redaktor",
I'd say "Live Redaktor" is more correct.

2024-07-30 06:24 UTC, chirbard commented on packages/docusaurus-theme-translations/locales/et/theme-search-algolia.json
> +  "theme.SearchModal.footer.closeKeyAriaLabel": "Paoklahv nuppu",
"Paoklahvi"

2024-07-30 06:25 UTC, chirbard reviewed
Added some comments that should be fixed. Everything else looks good to me.

2024-07-30 06:25 UTC, chirbard commented on packages/docusaurus-theme-translations/locales/et/theme-search-algolia.json
> +  "theme.SearchModal.footer.selectKeyAriaLabel": "Sisestusklahv nuppu",
"Sisestusklahvi"

2024-07-30 07:44 UTC, Gekd reviewed
Fixed your comments.

2024-07-30 10:13 UTC, chirbard reviewed
LGTM

2024-07-30 14:51 UTC, slorber commented
@Gekd thanks

We need you to sign the CLA. I can't merge the PR otherwise.

2024-08-09 10:00 UTC, Gekd commented
Signed CLA.

2024-08-09 10:13 UTC, merged