Add Render hosting guide
facebook/docusaurus pull request #1615
Opened 2019-06-19 20:46 UTC by anurag

## Motivation

[Render](https://render.com) is an official deployment option for [create-react-app](https://facebook.github.io/create-react-app/docs/deployment#render-https-rendercom), [gatsby](https://www.gatsbyjs.org/docs/deploying-to-render/), and [hugo](https://gohugo.io/hosting-and-deployment/hosting-on-render/). This PR adds a guide for Docusaurus users who may want to host their site on Render.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan
- [x] `yarn prettier && yarn lint`
- [x] `yarn test`
- [x] Visual inspection of all doc versions.

2019-07-12 04:38 UTC, yangshun requested changes
Sorry for the late review. The PR looks ok but can we leave out updating the old versioned docs? The whole intention of versioning is to freeze old versions and new stuff should only go into new versions.

2019-07-12 05:05 UTC, anurag commented
Makes sense and will submit an update shortly.

On Thu, Jul 11, 2019 at 9:38 PM Yangshun Tay <notifications@github.com>
wrote:

> *@yangshun* requested changes on this pull request.
>
> Sorry for the late review. The PR looks ok but can we leave out updating
> the old versioned docs? The whole intention of versioning is to freeze old
> versions and new stuff should only go into new versions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/docusaurus/pull/1615?email_source=notifications&email_token=AAAOUANEX5XBSAVFHI5PD5TP7ADEZA5CNFSM4HZNGQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB6HWKCI#pullrequestreview-261055753>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAOUAJT5QPTW3PBONXY33TP7ADEZANCNFSM4HZNGQAQ>
> .
>

2019-07-12 05:34 UTC, anurag commented
> Sorry for the late review. The PR looks ok but can we leave out updating the old versioned docs? The whole intention of versioning is to freeze old versions and new stuff should only go into new versions.

@yangshun PR updated.

2019-07-12 05:54 UTC, endiliey requested changes
deploying for docusaurus 2 is slightly different.

2019-07-12 05:54 UTC, endiliey commented on website/docs/deployment.md
> +    | **Publish Directory** | `website/build/<projectName>` |
this is no longer true for docusaurus 2. projectname is not needed anymore

2019-07-12 15:12 UTC, endiliey approved these changes
lgtm

2019-07-12 16:58 UTC, yangshun approved these changes
Thank you!

2019-07-12 16:58 UTC, merged

2026-06-12 11:41 UTC, slorber commented
FYI, we are going to clean up our existing Docusaurus docs deployment page in favor of a GitHub discussions category. 

This means your platform won't appear anymore on this page: https://docusaurus.io/docs/deployment

If you want your hosting / CI / CDN platform to remain documented for Docusaurus users, please submit an entry at: https://github.com/facebook/docusaurus/discussions/categories/deployment-platforms

This will be your responsibility to keep it up to date over time.