feat: new docusaurus clear command
facebook/docusaurus pull request #3446
Opened 2020-09-13 03:33 UTC by abadon7

## Motivation
Implementing a new clear command to help users before reporting bugs as described in #3370 
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
yarn start:
No errors found.
![Clear1](https://user-images.githubusercontent.com/823453/93009475-3cd07900-f547-11ea-8403-586978c34170.jpg)

yarn clear:
Done message, no errors with the new command.
![Clear2](https://user-images.githubusercontent.com/823453/93009479-5a9dde00-f547-11ea-9ce7-8527706b934d.jpg)

System complaining because something is missing during run time
![Clear4](https://user-images.githubusercontent.com/823453/93009484-68ebfa00-f547-11ea-85d2-8a8325a3f99e.jpg)
![Clear3](https://user-images.githubusercontent.com/823453/93009485-6b4e5400-f547-11ea-8900-45f016f4b70b.jpg)

yarn start:
Everything is back to normal and working again.
![Clear5](https://user-images.githubusercontent.com/823453/93009494-8f119a00-f547-11ea-8571-0252096319be.jpg)
![Clear6](https://user-images.githubusercontent.com/823453/93009509-ca13cd80-f547-11ea-8202-80091e6f41dd.jpg)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

2020-09-16 08:02 UTC, lex111 requested changes
Thank you for your contribution, but we still need to document the new command in the master docs.

2020-09-16 08:02 UTC, lex111 commented on packages/docusaurus/bin/docusaurus.js
> +  .description('Clean website')
I think this change will improve understanding of the CLI command.

```suggestion
  .description('Remove build artifacts')
```

2020-09-17 04:52 UTC, abadon7 commented
> Thank you for your contribution, but we still need to document the new command in the master docs.

Hi @lex111, is here where I should document the new command?, https://v2.docusaurus.io/docs/cli

2020-09-17 06:06 UTC, lex111 commented
> Hi @lex111, is here where I should document the new command?, https://v2.docusaurus.io/docs/cli

Yes, please.

2020-09-25 02:33 UTC, abadon7 commented
> > Hi @lex111, is here where I should document the new command?, https://v2.docusaurus.io/docs/cli
> 
> Yes, please.
Hi @lex111, is everything ok?, please, let me know is anything else is needed.

2020-09-25 06:40 UTC, lex111 requested changes

2020-09-25 06:40 UTC, lex111 commented on website/docs/cli.md
> +Remove build artifacts.
Need to explain in more detail which folders are removed by this command.

2020-09-28 14:05 UTC, slorber commented
Thanks

Did some little changes and added more doc, will merge when CI completes

2020-09-28 14:33 UTC, merged

2020-09-28 15:55 UTC, abadon7 commented
@slorber and @lex111 Thank you for supporting me and allowing me to contribute to this project. I'll start the hunt for more things that I can help with.

2020-09-28 16:15 UTC, slorber commented
Thank you :) 

I've tagged a few starter issues, and guess some of them are still available