docs(v2): adding and specifying powershell and cmd for deployment in windows section
facebook/docusaurus pull request #3459
Opened 2020-09-17 14:15 UTC by jeremyhager

- Specified batch command is for cmd
- Added powershell as an option for deployment, changed outer quotes to single in deployment command
- This affects the following versioned docs:
  - 2.0.0-alpha.63
  - 2.0.0-alpha.64
  - Next (Dev)

## Motivation
Refs: #3389

The documentation for deploying in a Windows environment may not be as specific as it needs to be, example issue: #3389. Because of this I have added a powershell command for Windows and have specified that one is for command prompt (title cmd) and the other is for PowerShell (title powershell). 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
1. ran `yarn build`
2. `cd website`
3. `yarn start`
4. Implemented changes
5. Confirmed changes were made on versioned docs specified above

**Current (before changes):**
![image](https://user-images.githubusercontent.com/47301461/93482921-14cd7680-f8b5-11ea-823e-bcd7328e9e2e.png)

**Proposed (after changes):**
![image](https://user-images.githubusercontent.com/47301461/93482312-6b868080-f8b4-11ea-805e-01511a48aed7.png)

## Related PRs.
N/A

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

2020-09-17 17:11 UTC, lex111 reviewed
How about using tabs for this docs change?

See https://v2.docusaurus.io/docs/markdown-features/#tabs

2020-09-17 19:30 UTC, jeremyhager commented
I've updated the docs to include the change - bundled bash, powershell, and cmd together so they are all tabs:
![image](https://user-images.githubusercontent.com/47301461/93518354-8d4a2c80-f8e1-11ea-9a19-00603b5d2b14.png)

(bash is default). Let me know what you think

2020-09-18 07:32 UTC, lex111 requested changes
Let's stick to following order: Bash - Windows (instead of "cmd")- PowerShell

2020-09-18 14:44 UTC, jeremyhager commented
Done and done. Noticed you specified "**B**ash" vs "_b_ash" as well as "**P**ower**S**hell", so I've updated the labels to reflect that:
![image](https://user-images.githubusercontent.com/47301461/93611116-bd95d780-f982-11ea-851d-6e054af128cd.png)

Had some issues with spaces and using `<Tab>` strangely, however it's been resolved now.

2020-09-19 07:14 UTC, lex111 approved these changes

2020-09-19 07:16 UTC, merged

2020-09-19 07:16 UTC, lex111 commented
@jeremyhager thank you!

2020-09-19 17:30 UTC, jeremyhager commented
Thank you!!