Added Axioms to users
facebook/docusaurus pull request #3556
Opened 2020-10-08 10:31 UTC by abhishektiwari

Added Axioms to users (users.js)

2020-10-08 10:35 UTC, abhishektiwari commented
Signed Facebook CLA.

2020-10-08 11:00 UTC, slorber requested changes
Thanks!

LGTM, just add the image/svg to our repo instead of a remote url

2020-10-08 11:00 UTC, slorber commented on website-1.x/data/users.js
> +    image: 'https://static.axioms.io/branding/favicon.svg',
To avoid future broken images we ask to add the image directly in the repo.

2020-10-08 11:02 UTC, lex111 requested changes
Hi @abhishektiwari you are using v2 so you need to add your project to the proper file  - https://github.com/facebook/docusaurus/blob/master/website/src/data/users.js (because now you have added it to showcase for v1).

You will also need to upload a preview.

2020-10-08 12:53 UTC, slorber commented
Ah good catch :) though it was a v1 site due to no dark mode toggle presence

2020-10-08 23:46 UTC, abhishektiwari commented
@slorber @lex111 thanks. I will raise an updated pull request.

2020-10-09 07:31 UTC, slorber commented on website/src/data/users.js
> +    caption: 'Axioms',
```suggestion
    title: 'Axioms',
```

caption was for v1

2020-10-09 07:31 UTC, slorber commented on website/src/data/users.js
> +    infoLink: 'https://developer.axioms.io/',
```suggestion
    website: 'https://developer.axioms.io/',
```

2020-10-09 08:12 UTC, merged