Docs improve
facebook/docusaurus pull request #4259
Opened 2021-02-21 09:47 UTC by massoudmaboudi

## Motivation

This part was missing in the documents and it is kinda useful to have this kinda referencing.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Run yarn run start:v2 and check that the page http://localhost:3000/ is rendered properly.

## Related PRs

No

2021-02-22 11:47 UTC, massoudmaboudi commented
I added 'npm run swizzle' instead of 'docusaurus swizzle' because we use npx to install the documentation. So, when we use 'docusaurus swizzle', it shows an error that 'docusaurus: command not found'.

2021-02-22 11:50 UTC, massoudmaboudi commented
I added the blog reference part while compiling, blog/2021-01-02-hello-there` will be converted to `blog/2021/01/02/hello-there` in the URL. For a normal user, this conversion is mysterious. But this explanation can remove this issue.

2021-02-22 15:04 UTC, slorber approved these changes
thanks, will just add the npm2yarn tabs everywhere :)

2021-02-22 15:04 UTC, slorber commented on website/docs/using-themes.md
>  ```shell
```suggestion
```bash npm2yarn
```

will add npm/yarn tabs

2021-02-22 15:04 UTC, slorber commented on website/docs/cli.md
>  ```bash
```suggestion
```bash npm2yarn
```

Will add npm/yarrn tabs

2021-02-22 15:04 UTC, slorber commented on website/docs/cli.md
>  ```shell
```suggestion
```bash npm2yarn
```

2021-02-22 15:09 UTC, slorber requested changes
@massoudmaboudi please make smaller pull requests instead of one big that do multiple things.

I'm willing to merge:
- the fa translation file
- the CLI-related doc changes

But I'm not really willing to merge the "referencing blog posts" doc. 

If you made 3 separate PRs I would have been able to merge 2 of the 3 ;)

2021-02-22 19:16 UTC, slorber commented
Extracted the fa translations to https://github.com/facebook/docusaurus/pull/4271

Will clean up the current PR from the "referencing" section and merge it, but feel free to resubmit it if you feel we should add more doc, but to me, this has nothing to do with the markdown features, it's just a regular link.

Here's a "backup" of your doc in case you find this useful:

```
## Referencing blog posts

If you want to reference a blog post file, you could use the name of the post you want to reference.

For example, if you are in `folder/doc1.md` and you want to reference `blog/2021-01-02-hello-there.md`:

```md
---
title: Hello There
---
```

You can add a slug to a blog post in its metadata. Consider another blog post named `blog/2021-01-08-bye-everyone.md`:

```md
---
title: Bye Everyone
slug: bye-everyone
---
```

I am referencing a blog post in `../../blog/2021/01/02/hello-there`.

Reference to another blog post with a slug in `../../blog/bye-everyone`.

:::caution Be careful that we should convert the address of the blog post without slug from:

`blog/2021-01-02-hello-there` to `blog/2021/01/02/hello-there` :::
```

2021-02-22 19:38 UTC, merged

2021-02-22 20:09 UTC, massoudmaboudi commented
@slorber 
If you think it is not a good idea to add the blog referencing, then I will close the PR willingly.

2021-02-23 11:39 UTC, slorber commented
I don't think it's a good idea, it's just a regular link nothing else. If we were to add this kind of doc, it couldn't be related to "markdown features" nor the blog, but be more generic, because it's just a link, and the link in md or in blog posts or in page is the same concept under the hood