fix: fix links to JSON from .md files
facebook/docusaurus pull request #4827
Opened 2021-05-21 13:10 UTC by antmcc49

closes #3561
It seems to be a common problem that many people are having see:
https://stackoverflow.com/questions/65307533/link-to-static-json-file

Co-authored-by: Anthony McCaigue <anthony@nquiringminds.com>
Co-authored-by: Alois Klink <alois@nquiringminds.com>

## Motivation

(Write your motivation here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

2021-06-03 09:55 UTC, slorber requested changes
Thanks for contributing.

I'm not sure to understand what the problem is in the first place, and also why your solution is a good one.

Please give me context so that I understand better.

Also please add an example in one of our dogfooding pages, I suggest to add something in `src/pages/markdown-tests.md`, so that we are sure it works and that it keeps working over time.

I tried the following and it didn't seem to work

```
## Link to JSON file

- [manifest md link](@site/static/manifest.json)

- <a href={require("@site/static/manifest.json").default}>manifest jsx link</a>
```

2021-06-03 09:55 UTC, slorber commented on packages/docusaurus/src/webpack/utils.ts
> +      exclude: new RegExp(`"/${STATIC_DIR_NAME}/"`), // exclude static dir
is it normal to have " around the path?

won't this kick in for any /static/ folder (what if users have src/pages/static/xyz for example?)

What about the else case (babelOptions object?)

2021-11-18 09:31 UTC, Josh-Cena commented
The right fix should be: in Markdown links, JSON extensions should be converted to `!!file-loader!` calls instead of using Babel loader. This would be done on the `mdx-loader` side instead.

2021-11-21 02:31 UTC, Josh-Cena commented
I'm taking this over. However this is much harder as it seems, because Webpack 4+ automatically loads JSON as data even with file-loader. (https://github.com/webpack-contrib/file-loader/issues/259, https://github.com/webpack/webpack/issues/6586)

We are migrating to asset modules (#4708) but probably not in a while due to blocking issues about plugin compatibility. I'll see what are the possibilities to solve this. currently build is failing, which is expected.

2022-01-23 03:45 UTC, Josh-Cena commented
Fair. I doubt if this is used a lot anyways, and for the rest there's no behavior difference. Will merge it since it's just temporary

2022-01-23 03:46 UTC, merged