feat(content-blog): allow sorting posts in ascending order
facebook/docusaurus pull request #5787
Opened 2021-10-25 21:50 UTC by cerkiewny

## Motivation

Solves #5692

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Regression tests for older relevant tests.
Created new test that sorts posts in reverse creation order and compare it to default option.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

2021-10-29 23:55 UTC, Josh-Cena commented
> Sure, sounds good I'll resubmit PR at the end or just after weekend

No need to close the current one, just change the current one

2021-10-30 05:58 UTC, cerkiewny commented
> > Sure, sounds good I'll resubmit PR at the end or just after weekend
> 
> No need to close the current one, just change the current one
I meant I will resubmit this one :p

2021-11-08 11:18 UTC, Josh-Cena requested changes
I think it mostly looks good in terms of implementation. In terms of whether we want this API or not... not sure🤔

Several API design suggestions:

- `postSortDirection` => `sortPosts` (we can have other options in the future)
- `'desc'` => `'descending'` (it's better to be explicit IMO)

2021-11-08 11:18 UTC, Josh-Cena commented on website/docs/api/plugins/plugin-content-blog.md
> +| `postSortDirection` | `string` | `'desc'` | One of 'desc', 'asc'. Governs the direction of blog post sorting. |
```suggestion
| `postSortDirection` | <code>'asc' \| 'desc'</code> | `'desc'` | Governs the direction of blog post sorting. |
```

Maybe also rename to `'ascending' | 'descending'`? I think it's your C idiom kicking in again 😄

2021-11-08 11:18 UTC, Josh-Cena commented on packages/docusaurus-plugin-content-blog/src/types.ts
> +  postSortDirection: string;
```suggestion
  postSortDirection: 'asc' | 'desc';
```

Use union type to constrain to only two values.

2021-11-09 09:43 UTC, Josh-Cena commented on website/docs/api/plugins/plugin-content-blog.md
> +| `postSorting` | <code>'descending' \| 'ascending' </code> | `'descending'` | Governs the direction of blog post sorting. |
```suggestion
| `sortPosts` | <code>'descending' \| 'ascending' </code> | `'descending'` | Governs the direction of blog post sorting. |
```

2021-11-09 09:47 UTC, Josh-Cena approved these changes
LGTM. Looking for @slorber

2021-11-09 17:25 UTC, slorber commented
LGTM

`sortPosts` is nice, gives the opportunity to eventually use a fn later if we change our mind

2021-11-09 17:25 UTC, merged

2024-02-09 16:31 UTC, slorber commented
Just curious, are you using this feature @cerkiewny?

Do you expect the RSS feed to be in ascending order too? 🤔 

Asking for https://github.com/facebook/docusaurus/issues/9827#issuecomment-1936229920