Provide guidance for content protection options
facebook/docusaurus pull request #7064
Opened 2022-03-30 00:08 UTC by pizzaz93

Provide guidance for content protection options, this is based on a request and content in https://github.com/facebook/docusaurus/issues/6890.

2022-03-30 00:10 UTC, pizzaz93 commented
I just signed the CLA may take a few minutes to propogate.

2022-03-30 04:03 UTC, Josh-Cena requested changes
I have a feeling that you don't fully understand the implications behind "Docusaurus authentication", but anyways, spending more time on this would be worthwhile :)

2022-03-30 04:03 UTC, Josh-Cena commented on website/docs/deployment.mdx
> +3. A self service option, implementing client-side rendering routes and fetching content from a protected API, [Gatsby.js](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-aut
While I'm okay to have the other two in the documentation (though not very happy to), this is a part that we should NOT include. Gatsby is a direct replacement for Docusaurus. We are interested in how _we_ can do it, not how _they_ do it.

> - `addRoute({path: "/admin/*",component: "@site/src/Admin"})`
> - Admin should statically render a spinner or login page on the server => `/admin/index.html`
> - add Netlify redirect from `/admin/*` to `/admin/index.html` (for all i18n languages)
> - Use client-side route components in Admin after mount
> - Use API with authentication to fetch data at runtime in Admin routes

This part is the most relevant in https://github.com/facebook/docusaurus/issues/958#issuecomment-1057075925, all the other content is actually just "references" or "status quo". However, this instruction is quite vague—you probably need to actually implement that first as POC, and from there we can discuss which parts to include in the documentation.

2022-03-30 21:13 UTC, pizzaz93 commented on website/docs/deployment.mdx
> +3. A self service option, implementing client-side rendering routes and fetching content from a protected API, [Gatsby.js](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-aut
@Josh-Cena in terms of implementing a POC that would probably be beyond me, in scoping this pull request as a documentation add would we want to add those first two items?
Or alternatively reverting this PR and bundling that POC and documentation edit in one PR.

2022-03-31 04:15 UTC, Josh-Cena commented on website/docs/deployment.mdx
> +3. A self service option, implementing client-side rendering routes and fetching content from a protected API, [Gatsby.js](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-aut
TBF, I'm not entirely sure how we would progress. The first two points can be sufficient for a lot of users, but without the third point (written in a clear and instructive way) the doc seems obviously incomplete. Let's hold it as this until I (or someone else) figure out a way to move forward.

2022-04-06 16:37 UTC, slorber commented on website/docs/deployment.mdx
> +3. A self service option, implementing client-side rendering routes and fetching content from a protected API, [Gatsby.js](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-aut
yes, having a POC seems useful otherwise we are advising things that we didn't even try 😅

2022-04-06 16:41 UTC, slorber commented on website/docs/deployment.mdx
> +2. Cookie or OAuth workflow, CDNs with edge serverless functions support this feature set. For example, using [Cloudflare](#deploying-to-cloudflare-pages) workers an authentication workflow like [Git
technically edge serverless permits anything (including any SSO, Oauth, SAML, htaccess/password protection...) and it's what CDNs use themselves to handle 1). It's a bit like 1 and 2 are the same case somehow. Wonder what's the best way to present that.

2022-04-20 21:06 UTC, dprothero commented
FWIW, I have implemented an Okta integration on top of a Docusaurus site hosted by Netlify [using this library](https://github.com/twilio-labs/netlify-okta-auth).

2022-05-03 20:33 UTC, closed without merging

2023-05-23 02:13 UTC, massoudmaboudi commented
You may check my articles that show how to add an authentication layer to your Docusuaurs website.

https://iammassoud.net/blog/docusaurus-authentication-roadmap