add FAST to showcase
facebook/docusaurus pull request #7099
Opened 2022-04-01 21:30 UTC by huynhicode

## Motivation

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Run `yarn start`, view the changes on `http://localhost:3000/showcase` or `http://localhost:3000/showcase?name=fast`

## Related PRs

None

---

Screenshot:

![Screen Shot 2022-04-01 at 2 28 44 PM](https://user-images.githubusercontent.com/35910788/161343655-c19a3f82-ed8f-44ba-8347-5b740c5079aa.png)

2022-04-03 07:25 UTC, Josh-Cena commented
@huynhicode Please remember to sign the CLA. PRs without CLA will be closed after two weeks. Thanks!

2022-04-06 15:30 UTC, slorber requested changes
thanks, 

CLA signature is required

2022-04-06 15:32 UTC, slorber commented on website/src/data/users.tsx
> +    tags: ['opensource', 'product', 'design', 'large'],
doc is not particularly large + the design is not really related to Docusaurus itself

2022-04-07 04:32 UTC, Josh-Cena approved these changes
Thanks 👍 We can wait for the CLA as long as there's communication

2022-04-12 14:20 UTC, Josh-Cena commented
@huynhicode Any news?

2022-04-29 08:59 UTC, Josh-Cena commented
@huynhicode Hi, it's been another two weeks, any news?

I can appreciate how complicated these processes in big orgs can get, so don't get too stressed about it

2022-04-29 09:50 UTC, slorber commented
This CLA friction is too annoying for site showcase submissions 😅 

Trying to see if I can get approval to implement a simpler workflow where site owners would only have to comment on a GitHub issue, requesting to add their site to the showcase.

As long as it's us committing, it shouldn't require site owners to sign the CLA 🤷‍♂️ 

Related to https://github.com/facebook/docusaurus/issues/6882

2022-04-29 19:53 UTC, huynhicode commented
Hi @Josh-Cena Thanks for your patience, still pending approval.

@slorber That sounds like a great solution.

2022-05-07 12:20 UTC, Josh-Cena commented
@huynhicode Is it fine if we close this PR and I send a PR myself, crediting you as co-author?

2022-05-10 04:55 UTC, Josh-Cena commented
Thanks @EisenbergEffect I've sent https://github.com/facebook/docusaurus/pull/7384. Please take a look.

2022-05-14 15:47 UTC, closed without merging