fix(sitemap): exclude pages with robots noindex from sitemap
facebook/docusaurus pull request #7143
Opened 2022-04-09 14:31 UTC by Josh-Cena

## Motivation

fix #6247. I'm not sure if providing the entire helmet state would be too big as part of the plugin API, but currently it's the only way to get structured data about the head state. Otherwise, we can only export a string and then parse it again in `postBuild`, which sounds like too much overhead.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I reverted #7122 and added `<meta name="robots" content="noindex" />` to the debug layout. It turns out that these routes are still not included in the sitemap.

2022-04-13 17:21 UTC, slorber requested changes
Thanks 👍 

That looks to work nicely

Not fan of "helmet" name + public API surface, which makes it complex to document (also doc is missing)

2022-04-13 17:21 UTC, slorber commented on packages/docusaurus-plugin-sitemap/src/createSitemap.ts
> +  helmet: {[location: string]: HelmetServerState},
maybe rename to head?

2022-04-13 17:21 UTC, slorber commented on packages/docusaurus-plugin-sitemap/src/createSitemap.ts
> +  helmet: {[location: string]: HelmetServerState},
maybe rename to head?

2022-04-13 17:21 UTC, slorber commented on packages/docusaurus/src/commands/build.ts
> +        helmet: headTags,
maybe rename to head or headTags?

Not fan of using "helmet" name here, lib is an implementation detail and we already use "head" name in other places

Also not fan of the API surface it introduces.

Users shouldn't use something like `helmet[route]?.meta.toComponent()`, this is a quite confusing that we'd struggle to document well and ensure retrocompatibility on.

Maybe we could only expose a few route attributes and transform all `HelmetDatum` types to a convenient format, easy to document?

2022-04-13 17:21 UTC, slorber commented on packages/docusaurus/src/commands/build.ts
> +        helmet: headTags,
maybe rename to head or headTags?

Not fan of using "helmet" name here, lib is an implementation detail and we already use "head" name in other places

Also not fan of the API surface it introduces.

Users shouldn't use something like `helmet[route]?.meta.toComponent()`, this is a quite confusing that we'd struggle to document well and ensure retrocompatibility on.

Maybe we could only expose a few route attributes and transform all `HelmetDatum` types to a convenient format, easy to document?

2022-04-14 01:07 UTC, Josh-Cena commented on packages/docusaurus-plugin-debug/src/index.ts
> -export const routeBasePath = '__docusaurus/debug';
At least not as a public API. I also don't find this abstraction particularly useful

2022-04-14 09:05 UTC, slorber commented
> Not a fan of the API design either, but I can't find a nicer abstraction of the helmet state in a structured way.

I suggest we move on and merge this as it's a nice improvement for internal usage in the sitemaps plugin

We can document this behind an experimental flag, warn it may change and recommend to use "head" only in site plugins, not public/open-source plugins?

We don't flag any feature as experimental for now but we probably could as we have a few undocumented apis (like `useRouteContext`)

2022-04-14 09:19 UTC, Josh-Cena commented
We also have a `routes` prop passed to `postBuild` that's undocumented. Maybe we'll eventually remove that

2022-04-14 09:27 UTC, slorber commented
> We also have a routes prop passed to postBuild that's undocumented. Maybe we'll eventually remove that

🤷‍♂️ we might as well keep `routes` and assign the rendered metadata to items instead of having a separate object with head metadata. Both work, I just don't know what is more convenient to use (considering routes are deeply nested, metadata would only be added to the leaves final routes)

2022-04-14 09:28 UTC, slorber commented
I guess we can keep all this undocumented for now, let's merge as is 👍 

Hopefull if someone plans to use this they'll reach out and explain their use-case

2022-04-14 09:29 UTC, slorber approved these changes

2022-04-14 09:31 UTC, merged