Update home icon in breadcrumbs
facebook/docusaurus pull request #7183
Opened 2022-04-16 21:08 UTC by Dr-Electron

## Motivation

I think this improves the looks of the breadcrumbs

<img width="190" alt="old-light" src="https://user-images.githubusercontent.com/61637085/163691075-ebb1e831-22a9-4a5e-9df0-a61244d59423.png"><img width="190" alt="new-light" src="https://user-images.githubusercontent.com/61637085/163691100-dcda3412-8a0b-4139-9892-87ba4c2394e3.png">
<img width="190" alt="old-dark" src="https://user-images.githubusercontent.com/61637085/163691170-eccce9e4-8f7d-4cd1-bd8d-207e1d99d0d1.png"><img width="190" alt="new-dark" src="https://user-images.githubusercontent.com/61637085/163691193-4bb6bd2c-6326-4331-b1fc-65713d713b74.png">

I also gave an outlined version a quick try, but I think I still prefer the filled version 🤔 
Also a wider stroke didn't really made it better for my taste 😅 . But I'm happy to change if you like it better.
<img width="190" alt="new-outline-light" src="https://user-images.githubusercontent.com/61637085/163691289-c0b40447-858f-459b-8e5c-c21c8e0ec6b7.png"><img width="190" alt="new-outline-dark" src="https://user-images.githubusercontent.com/61637085/163691292-595972d3-6181-4527-bbd0-67ec704ed081.png">

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

2022-04-17 00:38 UTC, Josh-Cena commented on packages/docusaurus-theme-classic/src/theme/IconHome/index.tsx
> +
```suggestion

```

2022-04-17 00:38 UTC, Josh-Cena commented on packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/index.tsx
> +        <IconHome className={styles.icon}/>
```suggestion
        <IconHome className={styles.icon} />
```

2022-04-17 00:39 UTC, Josh-Cena requested changes
Can we use the primary color so it looks slightly more like a link?

2022-04-17 06:56 UTC, lex111 reviewed
Let's take the house icon from [the Google collection](https://fonts.google.com/icons?icon.query=home&icon.style=Filled)? It's more compact by size, just compare:

```
<svg height="24px" viewBox="0 0 24 24" width="24px" fill="currentColor"><path d="M0 0h24v24H0z" fill="none"/><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></svg>
```

2022-04-17 06:57 UTC, lex111 commented
> Can we use the primary color so it looks slightly more like a link?

It can be confusing, since primary color applies only to the active item of the breadcrumbs.

2022-04-17 08:09 UTC, Josh-Cena commented
> Let's take the house icon from [the Google collection](https://fonts.google.com/icons?icon.query=home&icon.style=Filled)?

That one has sharp edges, though, while all the other icons in our design system look "rounder". (I noticed a few do have square edges but I think we should update them as well, considering our boxes are round-cornered.) At best we need to edit that icon so it has rounded corners as well.

> since primary color applies only to the active item of the breadcrumbs.

Make sense

2022-04-17 09:56 UTC, lex111 commented
They provided the rounded variant too https://fonts.google.com/icons?icon.query=home&icon.style=Rounded

2022-04-17 09:58 UTC, Josh-Cena commented
Ah, that's nice!

2022-04-20 04:16 UTC, Josh-Cena commented
<img width="998" alt="Screen Shot 2022-04-20 at 12 15 32 PM" src="https://user-images.githubusercontent.com/55398995/164149330-46f8e12b-0c40-4757-ae2c-04b9ac9d2b54.png">

@lex111 FYI, there's a corner where the breadcrumb gets active state but not the link. Maybe you want to take a look?

2022-04-20 07:33 UTC, Josh-Cena commented
I think it should not be active when the cursor is not in that highlighted region. The background color should appear at the same instant as the text becomes green.

2022-04-20 12:41 UTC, slorber approved these changes
Thanks, LGTM 👍

2022-04-20 12:42 UTC, slorber commented
> The background color should appear at the same instant as the text becomes green.

Agree on that

There's something weird in Infima, because even hovering the "next" arrow, the background changes color immediately

2022-04-20 12:42 UTC, merged

2022-04-21 18:46 UTC, Dr-Electron commented
Thanks for fixing it and merging. Sorry that I didn't help. Was a busy week 😅