fix: autocollapse sidebar categories
facebook/docusaurus pull request #7411
Opened 2022-05-13 05:31 UTC by pranabdas

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: Existing tests should cover the changes.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Auto collapse sidebar categories when navigating via paginator. Trying to fix https://github.com/facebook/docusaurus/issues/7387

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs
https://github.com/facebook/docusaurus/issues/7387

2022-05-13 05:57 UTC, Josh-Cena requested changes
Thanks for the fix! The paginator navigation issue seems resolved, but now, when you are in a category: https://deploy-preview-7411--docusaurus-2.netlify.app/docs/advanced/plugins/, the entire category is not collapsible, which seems like bad UX to me. Could you take a look?

2022-05-13 08:13 UTC, pranabdas commented
@Josh-Cena Collapse button should be fine now, however one unintended change I see, if we click on non-category item it collapses previously opened category which used to be open prior to this change.

2022-05-13 08:18 UTC, Josh-Cena commented on packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category.tsx
>      }
```suggestion
    if (justBecameActive && collapsed) {
      setCollapsed(false);
    }
    if (autoCollapseCategories && !isActive && wasActive) {
      setCollapsed(true);
    }
```

2022-05-13 08:19 UTC, Josh-Cena commented
> if we click on non-category item it collapses previously opened category

I noticed that as well. If you can manage to fix it it would be neat, otherwise I'll take a look later

2022-05-13 08:26 UTC, Josh-Cena commented
Actually, it's because the fix is going in the wrong direction. We have two way to uncollapse a category: the "imperative" way through `setCollapsed`, and the "reactive" way through `updateCollapsed`, which also informs other categories to collapse themselves, you should pass the latter into `useAutoExpandActiveCategory` instead.

2022-05-13 15:27 UTC, pranabdas commented
@Josh-Cena now the behaviour seems correct.

2022-05-14 05:36 UTC, Josh-Cena approved these changes
Thanks!

Easier than I thought 😄

2022-05-14 05:37 UTC, merged