fix:(plugin-google-gtag) wrong document title is sent with gtag
facebook/docusaurus pull request #7424
Opened 2022-05-15 13:25 UTC by ori-shalom

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.

## Motivation

Fix issue https://github.com/facebook/docusaurus/issues/7420

## Test Plan

I manually tested it with the [reproduction environment on stackblitz](https://stackblitz.com/edit/github-fab3de?file=plugin%2Fclient-module.js).
I also have on my private project repo this implementation fix of the gtag plugin that I deployed and debuged using GA debug tools.
It can be clearly seen in the logs and in GA debug panel that the correct title is used now.

### Test links

https://stackblitz.com/edit/github-fab3de?file=plugin%2Fclient-module.js

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

2022-05-15 13:30 UTC, Josh-Cena requested changes
Please also add a brief comment explaining this, and linking to the issue.

2022-05-15 14:01 UTC, Josh-Cena approved these changes
This makes sense to me.

@slorber seems to dislike `setTimeout` for good reason, so I'll wait for his decision on this.

2022-05-19 16:49 UTC, ori-shalom commented
@slorber any comment on that?

2022-05-19 16:54 UTC, Kennysong55 commented
I can do docusaurus very well

On Thu, May 19, 2022, 5:50 PM Ori Shalom ***@***.***> wrote:

> @slorber <https://github.com/slorber> any comment on that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/docusaurus/pull/7424#issuecomment-1131952690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXZFXUCYADGPQPU3ANYD5DVKZWMBANCNFSM5V7DAPRA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-05-27 13:11 UTC, slorber commented
Related to https://github.com/facebook/docusaurus/pull/6732

I don't think we should ask all analytics plugin authors to use `setTimeout` (including ourselves)

I'd rather make it a guarantee that page metadatas/title are already updated when `routeDidUpdate` callback is fired

Some local tests:

<img width="760" alt="CleanShot 2022-05-27 at 15 05 07@2x" src="https://user-images.githubusercontent.com/749374/170705405-67b0ac8b-9d30-45e7-a51c-b61211ccf50b.png">

The easy solution would be to move to `useEffect` instead of `useLayoutEffect`: this is nice for analytics but likely not ideal for other use-cases where we need to update the DOM synchronously

2022-05-27 13:41 UTC, slorber commented
Waiting for an answer here: https://twitter.com/sebastienlorber/status/1530180431475265537

2022-05-27 14:40 UTC, slorber commented
Going to merge this, as at least it fixes the GTAG plugin for the next release

But clearly we are not done yet with those lifecycles, and this setTimeout should not be necessary

2022-05-27 14:48 UTC, merged