fix: `await` docMetaData and handle error
facebook/docusaurus pull request #8234
Opened 2022-10-21 06:30 UTC by shanpriyan

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

`await` the promise from `doProcessDocMetadata` and throw error if it fails

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs
Resolves #8230
Suggested fix [#8230 (comment)](https://github.com/facebook/docusaurus/issues/8230#issuecomment-1285163941)

2022-10-21 07:42 UTC, slorber requested changes
good start thanks 👍 

Can you also please add a unit test somewhere so that we be sure it works and never stops working again?

2022-10-21 07:42 UTC, slorber commented on packages/docusaurus-plugin-content-docs/src/docs.ts
> +    return docMetaData;
no need for intermediate var, just return await should be enough

2022-10-21 07:42 UTC, slorber commented on packages/docusaurus-plugin-content-docs/src/docs.ts
> +    throw new Error(`Can't process doc metadata for doc at path path=${args.docFile.filePath} in version name=${args.versionMetadata.versionName}`);
You can use Error Cause here:

https://2ality.com/2021/06/error-cause.html

2022-10-21 08:14 UTC, shanpriyan commented
>Can you also please add a unit test somewhere so that we be sure it works and never stops working again?

Actually I'm not very familiar with tests 😅, If you could guide me I'll add it. Any links similar tests would be appreciated

2022-10-21 08:26 UTC, slorber commented
You can get inspiration from: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts#L684

Create a md file with the bad frontmatter that should get rejected, then run the fn in a test and assert that the correct error message was thrown.

Run `yarn test docs.test.ts --watch` to run this specific test file. Jest provides `it.only(` and `describe.only(` to focus on a specific test case. 

Actually I think some existing tests might cover the error message already, and will start failing with your fix because the message is now updated to something better: you may have to change the assertions/snapshots to reflect the change. 

I'm not sure how Jest plays well with Error Cause, may have to look into it myself later. Let me know if you don't find a solution. If you want to contribute to open-source it will be important to be able to write tests so it's worth you give it a try ;)

2022-10-21 08:26 UTC, slorber commented on packages/docusaurus-plugin-content-docs/src/docs.ts
> +    throw new Error(`Can't process doc metadata for doc at path path=${args.docFile.filePath} in version name=${args.versionMetadata.versionName}`, {cause: err});
I think TS won't be happy because a catched error is of type "unknown"

you may need `err as Error`

2022-10-21 18:00 UTC, shanpriyan commented
>You can get inspiration from: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts#L684
>
>Create a md file with the bad frontmatter that should get rejected, then run the fn in a test and assert that the correct error message was thrown.
>
>Run yarn test docs.test.ts --watch to run this specific test file. Jest provides it.only( and describe.only( to focus on a specific test case.

This would be helpful to get started, thanks 

>If you want to contribute to open-source it will be important to be able to write tests so it's worth you give it a try ;)

😅 Will definitely consider your advice and I'll give this a try 🚀

2022-10-22 08:35 UTC, shanpriyan commented
>Actually I think some existing tests might cover the error message already, and will start failing with your fix because the message is now updated to something better: you may have to change the assertions/snapshots to reflect the change.

fixed existing test case (updated snapshot) which failed due to change in error message

|Before Fix|After fix|
|----|----|
|![image](https://user-images.githubusercontent.com/42532987/197329533-f26d59c9-324c-4b36-b31a-470a09370469.png)|![image](https://user-images.githubusercontent.com/42532987/197329553-c4e770ae-07f0-4263-8176-0afdf0a47877.png)

2022-10-22 11:30 UTC, shanpriyan commented
@slorber since the below _test case_ covers the latest error message (a532ed0576123a85b9fec6d354606009b5fa119d), Do I need to add a new _test case_? 

https://github.com/facebook/docusaurus/blob/e41133245ca4e6cee390da74ccfe305ccb2ddb25/packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts#L684

2022-10-26 12:21 UTC, slorber approved these changes
Thanks 👍 

Fixed the test to assert that we have the full error cause chain being tested

2022-10-26 12:48 UTC, merged