refactor(theme-classic) extract HomeBreadcrumbItem (#6953)
facebook/docusaurus pull request #8445
Opened 2022-12-15 15:28 UTC by 3v0k4

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

2022-12-15 15:50 UTC, 3v0k4 commented
Is `styles.breadcrumbsItemLink` unused code that we can remove?

2022-12-16 15:55 UTC, slorber requested changes
Thanks 👍 

See PR comments

<img width="664" alt="CleanShot 2022-12-16 at 16 55 05@2x" src="https://user-images.githubusercontent.com/749374/208137681-d975fa03-f84f-4b02-af2b-151d4a695904.png">

No need to, monorepos hoist and use local packages ;)

2022-12-16 15:55 UTC, slorber commented on packages/docusaurus-theme-classic/src/theme-classic.d.ts
> +declare module '@theme/DocBreadcrumbs/HomeBreadcrumbItem' {
Considering we are going to have multiple items I'd prefer to have something like `@theme/DocBreadcrumbs/Items/Home`

2022-12-16 15:55 UTC, slorber commented on packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/HomeBreadcrumbItem/index.tsx
> +        className={clsx('breadcrumbs__link', styles.breadcrumbsItemLink)}
indeed it looks like a dead style 👍 

```suggestion
        className="breadcrumbs__link"
```

2022-12-16 19:09 UTC, 3v0k4 commented
> See PR comments

✅

> No need to, monorepos hoist and use local packages ;)

TIL 🙏

2022-12-22 18:38 UTC, slorber approved these changes
Thanks 👍 LGTM

2022-12-22 18:40 UTC, slorber commented
hmmm, little CI failure that I will have to check, not your fault :)

2022-12-29 12:48 UTC, merged