chore: bump update-notifier
facebook/docusaurus pull request #8660
Opened 2023-02-13 13:57 UTC by layershifter

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

2023-02-13 21:53 UTC, Josh-Cena requested changes
Could you commit the lockfile changes?

2023-02-17 09:01 UTC, layershifter commented
> Could you commit the lockfile changes?

@Josh-Cena Oops, sorry missed that. As I see @slorber have already done that.

2023-02-17 10:18 UTC, merged

2023-03-31 11:16 UTC, kavinkuma6 commented
@slorber may I know when this change will get released? Asking because some changes merged before the date on which the current PR got merged were went in the release 2.4.0. I couldn't understand the release process.

2023-04-05 16:34 UTC, slorber commented
@kavinkuma6 all PRs target the upcoming v3 by default, unless we backport them to the v2 branch (and this one has not been backported)

You can use a canary release if you need this feature right now

2023-04-06 03:11 UTC, kavinkuma6 commented
> @kavinkuma6 all PRs target the upcoming v3 by default, unless we backport them to the v2 branch (and this one has not been backported)
> 
> You can use a canary release if you need this feature right now

Got it man. Thanks