Update DocNavbarItem error messages
facebook/docusaurus pull request #8735
Opened 2023-03-05 09:07 UTC by tannerdolby

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Improves the DocNavbarItem error messages to help new users understand that the Docusaurus config allows them to avoid the issue mentioned in https://github.com/facebook/docusaurus/discussions/8692 by updating `themeConfig.navbar.items`.

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

https://github.com/facebook/docusaurus/issues/8696

2023-03-08 18:12 UTC, slorber requested changes

2023-03-09 03:34 UTC, tannerdolby commented on packages/docusaurus-theme-common/src/utils/docsUtils.tsx
> +navbar items aren't attempting to reference a non-existent doc.
Gotcha! That makes sense. I've updated things to reflect your suggestions from https://github.com/facebook/docusaurus/issues/8696#issuecomment-1443395348

2023-03-09 16:57 UTC, slorber commented
Thanks

Did some modifications because the error page wasn't able to render the full error causal chain.

Now it will print everything:

![CleanShot 2023-03-09 at 17 55 31](https://user-images.githubusercontent.com/749374/224099355-1b0e8f1f-6ab8-4650-8b53-a2e529c1aa0f.png)

Not super pretty nor great DX, but message is clearer than before.

2023-03-09 17:31 UTC, slorber commented
Also found a generic solution to apply this automatically to all navbar items. It should make it easier for users to debug issues.

![CleanShot 2023-03-09 at 18 18 02](https://user-images.githubusercontent.com/749374/224105162-4c11a4ba-7be9-4235-9132-c74a6fca9f6e.png)

2023-03-09 17:56 UTC, merged

2023-03-09 20:05 UTC, tannerdolby commented
> Also found a generic solution to apply this automatically to all navbar items. It should make it easier for users to debug issues.

Nice work! Your generic solution works better and provides users a much easier way to debug the errors.