Version path & prefix configuration for plugin content docs
facebook/docusaurus pull request #8737
Opened 2023-03-05 22:39 UTC by Jersyfi

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

My personal motivation for modifying the `docusaurus-plugin-content-docs` plugin is to have more flexibility in the file structure. With this feature it is possible to group all files in one folder without having them in the project root folder.

## Test Plan

I have added a test folder called `versioned-site-with-custom-path` with the `versionPath` and `versionPrefix` options set and all files grouped together. In this state the tests are simple and I need your opinion if any changes are needed.

![image](https://user-images.githubusercontent.com/64214261/222989744-6d4b1d36-f0fb-44ad-865e-5944e5fe091c.png)

## Options

* `versionPath`
type: string | undefined
default: undefined
* `versionPrefix`
type: boolean
default: true

## Mofified Documentation

Page: website/docs/api/plugins/plugin-content-docs.mdx

## Related issues/PRs

https://github.com/facebook/docusaurus/issues/8061

2023-03-06 07:45 UTC, Jersyfi commented on website/docs/api/plugins/plugin-content-docs.mdx
> +| `versionPath` | `string` |  `''` | Path to versioned files on filesystem, relative to site dir. |
## TODO
Found that i missed changing the `versionPath` default value from `''` to `undefined`.
![image](https://user-images.githubusercontent.com/64214261/223048173-5ff2b87e-2498-4b92-8303-74e7f15b858a.png)

2023-03-06 11:16 UTC, Jersyfi commented on packages/docusaurus-plugin-content-docs/src/versions/files.ts
> +/** `[versionPath]/[pluginId?]_versioned_docs/version-1.0.0` */
Change the following comment word.
versionPath -> versionSiteDir

2023-03-06 11:16 UTC, Jersyfi commented on packages/docusaurus-plugin-content-docs/src/versions/files.ts
> +/** `[versionPath]/[pluginId?]_versioned_sidebars/version-1.0.0-sidebars.json` */
Change the following comment word.
versionPath -> versionSiteDir

2023-03-06 11:18 UTC, Jersyfi commented on packages/docusaurus-plugin-content-docs/src/versions/files.ts
> +/** `community` => `[versionPath]/community_versions.json` */
Change the following comment word.
versionPath -> versionSiteDir

2023-03-09 18:18 UTC, slorber requested changes
Looks like a good first draft

That probably solves your use-case, but I think this API is a bit awkward and not the most flexible either.

Reading the docs, it's not so clear to me what `versionPrefix` even is 😅

I'd prefer if we worked on designing the API we want first before doing the implementation.

For now, I think this API is more flexible than yours and less confusing:

```js
[
  "@docusaurus/plugin-content-docs",
  {
    id: "ios",
    path: "./ios-docs/v-next",
    versionPath: ({version}) => `./ios-docs/v-${version.toLowerCase().replace(".","-"}`,
  },
];
```

2023-04-24 20:22 UTC, Jersyfi commented
Closing the PR as there is no time for further changes.

2023-04-24 20:22 UTC, closed without merging