Added write premissions to GH workflow examples
facebook/docusaurus pull request #8877
Opened 2023-04-10 12:06 UTC by e-minguez

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fixes #8876

## Test Plan

None

### Test links

N/A

## Related issues/PRs

#8876

2023-04-11 01:23 UTC, Josh-Cena requested changes
Thank you! I don't think the issue link is necessary (you can either remove it or replace it with something like `# Explicitly grant write permission`), but otherwise this should be good.

2023-04-12 18:03 UTC, slorber reviewed
Thanks 👍 

Agree that the issue link is not needed

2023-04-12 18:03 UTC, slorber commented on website/docs/deployment.mdx
> +# https://github.com/peaceiris/actions-gh-pages/issues/852
```suggestion
```

2023-04-12 18:03 UTC, slorber commented on website/docs/deployment.mdx
> +# https://github.com/peaceiris/actions-gh-pages/issues/852
```suggestion
```

2023-04-13 08:04 UTC, merged