feat:Enhance the deploy command to enable the setting of git user.name and user.email in deployment branch (#9101)
facebook/docusaurus pull request #9102
Opened 2023-06-25 01:33 UTC by amdshrif

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fix for #9101

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

2023-06-29 10:28 UTC, slorber requested changes
Do we really need this?

What prevents from replacing:

```bash
export GIT_USER_NAME="xyz"
export GIT_USER_EMAIL="my@email.com"
yarn deploy
```

With:

```bash
git config user.name "xyz"
git config user.email "my@email.com"
yarn deploy
```

2023-06-29 10:28 UTC, slorber commented on packages/docusaurus/src/commands/deploy.ts
> +    }
not super fan of having config side-effects like this, and features without documentation

2023-06-29 22:11 UTC, amdshrif commented
> Do we really need this?
> 
> What prevents from replacing:
> 
> ```shell
> export GIT_USER_NAME="xyz"
> export GIT_USER_EMAIL="my@email.com"
> yarn deploy
> ```
> 
> With:
> 
> ```shell
> git config user.name "xyz"
> git config user.email "my@email.com"
> yarn deploy
> ```

The suggested enhancement will only update the user.name and user.email locally on the repo level, while keeping the global git config as-is and I do not have to bother to keep switching between the emails and names for every work I do on my machine. 

The new enhancement works well with a local shell script that exports the other env variable settings all together. 

env-setting.sh
```shell 
export USE_SSH=true
export GIT_USER="amdshrif"
export CURRENT_BRANCH="deployment"
export GIT_USER_NAME="Ahmad Shrif"
export GIT_USER_EMAIL="ahmad.shrif@gmail.com"
```
source env-settings.sh

2023-06-30 08:21 UTC, slorber commented
> The suggested enhancement will only update the user.name and user.email locally on the repo level, while keeping the global git config as-is and I do not have to bother to keep switching between personal and work emails for every work I do on my machine.

Sorry, but I don't understand your answer.

> The suggested enhancement will only update the user.name and user.email locally on the repo level, while keeping the global git config as-is

Isn't it the intended behavior in both cases?

---

I'll ask again:

Does the following work to deploy with the specified username/email, yes or not?

```sh
git config user.name "Ahmad Shrif"
git config user.email "ahmad.shrif@gmail.com"
yarn deploy
```

Have you tested it? 

If it does not work, can you tell me what's the behavior you see, and what's the behavior you want?

2023-06-30 08:34 UTC, slorber commented
Ok I understand the problem now, there are 2 repositories involved:
- The current one
- The one we clone for deployment (possibly a different one)

We need to set the config on the cloned deployment

I'm ok to merge this, but please add some documentation for these env variables

2023-06-30 21:55 UTC, amdshrif commented
> Ok I understand the problem now, there are 2 repositories involved:
> 
> * The current one
> * The one we clone for deployment (possibly a different one)
> 
> We need to set the config on the cloned deployment
> 
> I'm ok to merge this, but please add some documentation for these env variables

Yes, that the is correct. Actually it is one repository and two branches, when we run `yarn deploy` it does a clone for the repository with the selected branch in a tmp folder and pushes the changes from there.

I will update the PR to update the docs and testing.

2023-07-03 07:51 UTC, slorber commented
Thanks, added the docs to your pr already :)

2023-07-03 07:51 UTC, merged