feat(core): generate meta og locale and alternates issue #8887
facebook/docusaurus pull request #9152
Opened 2023-07-17 14:21 UTC by FlorinaPacurar

## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [X] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fixes issue #8887 by adding og locale and alternates

## Test Plan

Tested locally in browser with suggested config
![Screenshot 2023-07-17 at 17 13 04](https://github.com/facebook/docusaurus/assets/112615592/92a92043-b2fc-4e47-97d6-5bb859a66ae2)

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

issue #8887

2023-07-27 15:38 UTC, slorber requested changes
Thanks, almost looks good.

This should rather be handled in `theme/SiteMetadata` (theme) instead of `SiteMetadataDefaults` because supporting og locale attributes is opinionated, shouldn't be mandatory for users and we should give them the ability to remove support if they don't want it (which would reduce the size of the html pages).

See location of original PR here: https://github.com/facebook/docusaurus/pull/8894

2023-07-28 09:11 UTC, FlorinaPacurar commented
Thanks @slorber - updated.

2023-07-28 09:35 UTC, slorber requested changes
Looks good 👍 just requesting minor code changes

2023-07-28 09:35 UTC, slorber commented on packages/docusaurus-theme-classic/src/theme/SiteMetadata/index.tsx
> +  const currentHtmlLang = localeConfigs[currentLocale]?.htmlLang;
```suggestion
  const currentHtmlLang = localeConfigs[currentLocale]!.htmlLang;
```

We can assume each locale will have a config in the map

2023-07-28 09:35 UTC, slorber commented on packages/docusaurus-theme-classic/src/theme/SiteMetadata/index.tsx
> +  const bcp47ToLocale = (code: string): string => code.replace('-', '_');
```suggestion
  const bcp47ToOpenGraphLocale = (code: string): string => code.replace('-', '_');
```

More explicit fn name

2023-07-28 09:35 UTC, slorber commented on packages/docusaurus-theme-classic/src/theme/SiteMetadata/index.tsx
> +      {currentHtmlLang && (
Now `currentHtmlLang` can't be undefined so this condition is useless

2023-07-28 14:02 UTC, slorber approved these changes
LGTM thanks 👍

2023-07-28 15:16 UTC, merged