feat(a11y): Fix a11y in sidebar
facebook/docusaurus pull request #9269
Opened 2023-08-28 14:07 UTC by pinakipb2

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).

## Motivation

Fixes #9162

## Test Plan

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

#9162

2023-08-31 09:58 UTC, slorber requested changes
Reading https://github.com/facebook/docusaurus/pull/9269, I'm not 100% sure it's what @msftedad want, but we'll see when they review.

I'd prefer if you didn't duplicate the button JSX because only 1 prop is different for the 2 cases

2023-08-31 09:58 UTC, slorber commented on packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx
> +          description: 'The ARIA label to expand the sidebar category',
we could have a ternary only on the aria-label prop instead of having 2 different button JSX here

2023-08-31 09:58 UTC, slorber commented
@msftedad can you please review this PR and tell us if it improves accessibility for you? 

Preview url: https://deploy-preview-9269--docusaurus-2.netlify.app/

Thanks

2023-09-01 16:16 UTC, pinakipb2 commented
Hi @slorber its not "fix(a11y): fix docs sidebar category caret button accessibility, improve aria-label" as its not only for docs, it will affect the sidebar on every page using docusaurus. Its a change on the main product. The sidebar of the generated sites will have this a11y. Its better for users with screen readers to know if the sidebar category button is expand/collapse type so that they know the action they are performing.

2023-09-01 17:54 UTC, pinakipb2 commented
> > Hi @slorber its not **"fix(a11y): fix docs sidebar category caret button accessibility, improve aria-label"** as its not only for docs, it will affect the sidebar on every page using docusaurus. Its a change on the main product. The sidebar of the generated sites will have this a11y. Its better for users with screen readers to know if the sidebar category button is expand/collapse type so that they know the action they are performing.
> > _Ignore if you mean the documentation site(site generated by docusaurus) as docs._
> 
> Sorry but I don't understand 😅

Hi @slorber, people who are visually impaired rely on screen readers, the screen readers read the content of the website to them. But some complex components like button with a icon, its really hard for them(screen readers) to know the function of the button, and they don't know what to say aloud. So aria-label is used to so that they know what the button does and they say that aloud. So, in sidebar, in dropdown now the screen reader will say if the dropdown is collapsed on expanded, so the visually impaired person can know if clicking it will collapse the menu or expand it.
![image](https://github.com/facebook/docusaurus/assets/48859773/511efaa6-fd77-4456-a424-0c7ce194abfc)

Hope you understand it now.

2023-09-05 05:33 UTC, pinakipb2 commented
@slorber @msftedad Have a look !

2023-09-11 17:52 UTC, pinakipb2 commented
@slorber @msftedad Have a look on the PR !

2023-09-12 17:14 UTC, pinakipb2 commented
Hi @slorber, as mentioned in https://github.com/facebook/docusaurus/issues/9162#issuecomment-1714937042 by @msftedad, you can now merge this PR.
Thanks !

2023-09-14 08:41 UTC, slorber approved these changes
Thanks 👍 

Just renamed the "isActive" props to "collapsed" because it's not super clear what isActive means if we extract later the button to a separate file

2023-09-14 11:01 UTC, merged