fix(theme-classic): fixed wrong cursor on dropdown menu in navbar, when window is small
facebook/docusaurus pull request #9398
Opened 2023-10-12 15:39 UTC by Shreesh09

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation
Fixed the issue where wrong cursor was displaying when hovering over any dropdown menu present in the navbar, when the screen size is small

## Test Plan

Incorrect cursor:
![without-fix](https://github.com/facebook/docusaurus/assets/114166000/3c73831c-815f-452a-882c-e4ad6d4f01a3)

Correct cursor:
![with-fix](https://github.com/facebook/docusaurus/assets/114166000/035ec756-c495-4f8f-9c21-56a0c94ad2e2)

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs
#8485

2023-10-12 16:19 UTC, Josh-Cena commented
Please use CSS instead. This link is not a link, so it should not have an `href`.

2023-10-12 16:52 UTC, Shreesh09 commented
> Please use CSS instead. This link is not a link, so it should not have an `href`.

I am simply replicating how the dropdown menu currently behaves in the navbar when the screen size is normal, is that incorrect aswell?

![dropdown](https://github.com/facebook/docusaurus/assets/114166000/3d05c06b-cc97-45e9-9051-99ced39e0cf2)

2023-10-14 03:01 UTC, Shreesh09 commented
Hello @Josh-Cena, I have implemented the changes. Could you please take a moment to review them? Thank you.

2023-10-16 01:41 UTC, Josh-Cena commented on packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem/index.tsx
> +      className={clsx(styles.dropdownNavbarItemMobile, 'menu__list-item', {
Why is it called `dropdownNavbarItemMobile`? It's used on desktop, right?

2023-10-16 01:41 UTC, Josh-Cena approved these changes
You would need to format your code. You can copy this file into https://prettier.io/playground/ if you don't have a local clone. Otherwise, this should be good.

2023-10-16 01:42 UTC, Josh-Cena commented on packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem/index.tsx
> +      className={clsx(styles.dropdownNavbarItemMobile, 'menu__list-item', {
Never mind, this is only for mobile :)

2023-10-16 02:32 UTC, Shreesh09 commented
I believe the code is properly formatted because after copy pasting from prettier and then commiting the code remains unchanged

2023-10-16 02:41 UTC, Josh-Cena commented
I see. You are right.

2023-11-15 17:58 UTC, Josh-Cena approved these changes
LGTM, thanks :)

2023-11-15 18:05 UTC, Josh-Cena requested changes
Actually, instead of applying this class to the `<li>`, we should apply it to the inner `<NavbarNavLink>`, because that's the one that should theoretically be a pointer, should there be an `href`. Do you want to do this change? I will do it in the upcoming days otherwise.

2023-11-15 18:16 UTC, Shreesh09 commented
Sure, I will make the changes.

2023-11-15 22:28 UTC, Josh-Cena approved these changes
Thanks for the timely responses!

2023-11-15 22:29 UTC, merged