fix(content-blog): add baseUrl for author.image_url
facebook/docusaurus pull request #9581
Opened 2023-11-24 15:53 UTC by OzakIOne

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fix: #9577 

## Test Plan

Local builds & unit tests 

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

#9577

2023-11-26 18:00 UTC, slorber requested changes
Thanks, almost good but a few changes needed

2023-11-26 18:00 UTC, slorber commented on packages/docusaurus-plugin-content-blog/src/authors.ts
> +    author.imageURL = path.join(baseUrl, author.imageURL);
`path.join` is not ideal for this situation.
Separator will be different depending on OS (`/` or `\`), that's why Windows tests fail
It's preferable to use our `normalizeUrl()` util

2023-11-26 18:00 UTC, slorber commented on packages/docusaurus-plugin-content-blog/src/authors.ts
> +  authors.forEach((author) => {
prefer FP style: use map and return new object instead of mutating input with side effect

2023-11-26 18:00 UTC, slorber commented on packages/docusaurus-plugin-content-blog/src/authors.ts
> +  }
duplicated logic, encapsulate in shared function

Also I think we should process all urls starting with `/`, not based on protocol. 
We should not process relative urls like `./img/author.png`

I'd use something like:

```js
function normalizeImageURL({imageURL,baseUrl}) {
  return imageURL.startsWith("/") ? normalizeUrl([baseUrl,imageURL)) : imageUrl
}
```

2023-11-27 01:19 UTC, Josh-Cena reviewed
Do we have tests for local image URLs (like `image: ./file.png`)? What's the current behavior, for front matter and for `authors.yml`?

2023-12-05 15:34 UTC, slorber commented
> Maybe it's just me but I'm using the static folder less and less—bundling everything seems more organized to me. Even with `authors.yml`, we should be able to specify an image relative to the yaml file.

agree, but we don't really support that currently. That's worth exploring how to implement this in another PR

LGTM thanks @OzakIOne 👍

2023-12-05 15:36 UTC, slorber approved these changes

2023-12-05 15:36 UTC, merged