feat(feed): apply trailing slash
facebook/docusaurus pull request #9920
Opened 2024-03-06 17:21 UTC by OzakIOne

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

tools like Algolia that use the feed files may behave unusual if trailing slash is enabled and not applied to links

## Test Plan

Deploy preview ??

### Test links

Deploy preview: https://deploy-preview-9920--docusaurus-2.netlify.app/

## Related issues/PRs

Fix #9829

2024-03-06 17:39 UTC, OzakIOne commented
Found a todo
https://github.com/facebook/docusaurus/blob/d7a7caec6d758eabc332e7e697a63e7c85279076/packages/docusaurus-utils-common/src/applyTrailingSlash.ts#L27-L30
I think we can do it in this PR however should we keep the one in `utils-common` or `utils` ?

2024-03-07 10:25 UTC, slorber commented
- `utils` is Node.js only utils
- `utils-common` is Browser + Node.js

This code is env agnostic so it should rather be in utils-common, but is not because this shared package was introduced later. I'd prefer if you did this refactor in another PR because this will impact various files unrelated to this feature.

2024-03-07 10:28 UTC, slorber requested changes

2024-03-07 10:28 UTC, slorber commented on packages/docusaurus-plugin-content-blog/src/feed.ts
> +      const blogPostAbsoluteUrl = applyTrailingSlash(
LGTM 👍 

We need a test in `feed.test.ts` covering this, maybe copy/paste `it('has feed item for each post'` and add the site trailing slash config?

2024-03-14 14:32 UTC, slorber approved these changes

2024-03-14 15:45 UTC, merged

2024-03-14 15:49 UTC, ilg-ul commented
Thank you!